import { dbClient } from "../db/client";
import type { EvidenceRecord } from "../db/schema";
import type { WritingArtifact } from "../writing/types";

import type {
  ApplicationPacket,
  ApprovalActionType,
  ApprovalEvidenceSummary,
  ApprovalGroundingSummary,
  ApprovalItem,
  ChecklistItem
} from "./types";

/**
 * ApprovalQueueSubagent.
 *
 * Turns a packet into a small set of typed approval items the user can act
 * on locally. Everything emitted here is a PENDING decision — nothing
 * generated by this subagent performs a side-effect, per CLAUDE.md §8
 * invariants 1–3 and agents.md §4.17.
 *
 * Item types emitted in this slice:
 *   - approve_draft         (writing artifact ready, waiting on user sign-off)
 *   - edit_required         (writing artifact has critic/style warnings)
 *   - missing_input         (checklist requires user data or documents)
 *   - ready_for_submission  (all required items green — still *not* a submit)
 *
 * `submit_application`, `pay_fee`, `send_email`, `approve_outreach` from
 * data-model.md §6.4 are intentionally not emitted here.
 */
export interface ApprovalQueueBuildInput {
  packet: ApplicationPacket;
}

function approvalId(packet: ApplicationPacket, suffix: string): string {
  return `approval_${packet.programId}__${suffix}`;
}

function groundingSummaryForArtifact(
  artifact: WritingArtifact
): ApprovalGroundingSummary {
  return {
    verifiableClaims: artifact.grounding.verifiableClaims,
    supportedClaims: artifact.grounding.supportedClaims,
    unsupportedClaims: artifact.grounding.unsupportedClaims.length,
    passed: artifact.grounding.passed,
    profileFieldKeys: artifact.usageSummary.profileFieldKeys,
    verifiedStoryIds: artifact.usageSummary.verifiedStoryIds,
    programIds: artifact.usageSummary.programIds,
    fundingIds: artifact.usageSummary.fundingIds,
    personRoleIds: artifact.usageSummary.personRoleIds,
    professionalProfileIds: artifact.usageSummary.professionalProfileIds,
    voiceAnchorId: artifact.usageSummary.voiceAnchorId
  };
}

function collectEvidenceIds(
  subjectType: string,
  subjectIds: readonly string[]
): EvidenceRecord[] {
  if (subjectIds.length === 0) return [];
  const ids = new Set(subjectIds);
  return dbClient.list(
    "evidence",
    (row) => row.subjectType === subjectType && ids.has(row.subjectId)
  );
}

function truncateQuote(text: string, max = 140): string {
  const compact = text.replace(/\s+/g, " ").trim();
  if (compact.length <= max) return compact;
  return `${compact.slice(0, max - 1)}…`;
}

function evidenceSummaryForPacket(
  packet: ApplicationPacket,
  artifact: WritingArtifact | null
): ApprovalEvidenceSummary {
  const programEvidence = collectEvidenceIds("graduateProgram", [
    packet.programId
  ]);
  const universityEvidence = collectEvidenceIds("university", [
    packet.universityId
  ]);
  const fundingEvidence = packet.fundingId
    ? collectEvidenceIds("fundingOpportunity", [packet.fundingId])
    : [];
  const personRoleEvidence = artifact?.usageSummary.personRoleIds.length
    ? collectEvidenceIds("personRole", artifact.usageSummary.personRoleIds)
    : packet.target.personRole
      ? collectEvidenceIds("personRole", [packet.target.personRole.id])
      : [];
  const profileEvidence = artifact?.usageSummary.professionalProfileIds.length
    ? collectEvidenceIds(
        "professionalProfile",
        artifact.usageSummary.professionalProfileIds
      )
    : [];

  const exampleQuotes: string[] = [];
  const candidatePool: EvidenceRecord[] = [
    ...programEvidence.slice(0, 2),
    ...fundingEvidence.slice(0, 2),
    ...personRoleEvidence.slice(0, 1),
    ...universityEvidence.slice(0, 1)
  ];
  for (const evidence of candidatePool) {
    if (exampleQuotes.length >= 5) break;
    exampleQuotes.push(
      `[${evidence.sourceLabel}] ${truncateQuote(evidence.quotedText)}`
    );
  }

  return {
    programEvidenceIds: programEvidence.map((row) => row.id),
    universityEvidenceIds: universityEvidence.map((row) => row.id),
    fundingEvidenceIds: fundingEvidence.map((row) => row.id),
    personRoleEvidenceIds: personRoleEvidence.map((row) => row.id),
    professionalProfileEvidenceIds: profileEvidence.map((row) => row.id),
    exampleQuotes
  };
}

function artifactForChecklistItem(
  packet: ApplicationPacket,
  item: ChecklistItem
): WritingArtifact | null {
  if (!item.writingRequestId) return null;
  return (
    packet.documents.find(
      (artifact) => artifact.request.id === item.writingRequestId
    ) ?? null
  );
}

function approveDraftItem(
  packet: ApplicationPacket,
  item: ChecklistItem
): ApprovalItem | null {
  const artifact = artifactForChecklistItem(packet, item);
  if (!artifact) return null;
  if (item.status !== "complete") return null;

  return {
    id: approvalId(packet, `approve_${item.kind}`),
    actionType: "approve_draft",
    status: "pending",
    defaultAction: "approve",
    userId: packet.userId,
    programId: packet.programId,
    universityId: packet.universityId,
    fundingId: packet.fundingId,
    artifactId: artifact.request.id,
    artifactKind: artifact.request.documentType,
    reason: `${item.label} passed grounding, critic, and style checks.`,
    actionRequired: "Review and approve draft before packaging.",
    grounding: groundingSummaryForArtifact(artifact),
    evidence: evidenceSummaryForPacket(packet, artifact),
    checklistItemIds: [item.id],
    createdAt: dbClient.now()
  };
}

function editRequiredItem(
  packet: ApplicationPacket,
  item: ChecklistItem
): ApprovalItem | null {
  const artifact = artifactForChecklistItem(packet, item);
  if (!artifact) return null;
  if (item.status !== "ready_with_warnings" && item.status !== "missing") {
    return null;
  }
  if (item.status === "missing" && artifact.grounding.passed) {
    return null;
  }

  const reason =
    item.status === "missing"
      ? `${item.label} draft failed grounding — ${artifact.grounding.unsupportedClaims.length} unsupported claim(s).`
      : `${item.label} draft needs edits: ${item.notes.join("; ") || "critic or style warnings present"}.`;

  return {
    id: approvalId(packet, `edit_${item.kind}`),
    actionType: "edit_required",
    status: "pending",
    defaultAction: "edit",
    userId: packet.userId,
    programId: packet.programId,
    universityId: packet.universityId,
    fundingId: packet.fundingId,
    artifactId: artifact.request.id,
    artifactKind: artifact.request.documentType,
    reason,
    actionRequired:
      "Open draft, address warnings, and re-run writing cycle before approval.",
    grounding: groundingSummaryForArtifact(artifact),
    evidence: evidenceSummaryForPacket(packet, artifact),
    checklistItemIds: [item.id],
    createdAt: dbClient.now()
  };
}

function missingInputItems(packet: ApplicationPacket): ApprovalItem[] {
  const items: ApprovalItem[] = [];
  for (const item of packet.checklist) {
    const isMissingCategory =
      item.status === "missing" || item.status === "needs_user_input";
    if (!isMissingCategory) continue;
    if (item.category === "document_draft" && item.writingRequestId) continue;

    const artifactLessMissing =
      item.category === "document_draft" && !item.writingRequestId;

    const reason = artifactLessMissing
      ? `${item.label} has no draft yet — re-run the writing cycle for this program.`
      : `${item.label} is missing from the profile revision.`;

    items.push({
      id: approvalId(packet, `missing_${item.kind}`),
      actionType: "missing_input",
      status: "pending",
      defaultAction: "edit",
      userId: packet.userId,
      programId: packet.programId,
      universityId: packet.universityId,
      fundingId: packet.fundingId,
      artifactId: null,
      artifactKind: item.writingDocumentType,
      reason,
      actionRequired: actionForMissing(item.kind),
      grounding: null,
      evidence: evidenceSummaryForPacket(packet, null),
      checklistItemIds: [item.id],
      createdAt: dbClient.now()
    });
  }
  return items;
}

function actionForMissing(kind: ChecklistItem["kind"]): string {
  switch (kind) {
    case "transcript":
      return "Attach undergraduate transcript as a source document on this revision.";
    case "test_score_report":
      return "Upload test score report (TOEFL / IELTS / GRE) as a source document.";
    case "application_fee_or_waiver":
      return "Record fee-waiver status or confirm fee payment plan for this program.";
    case "recommendation_letter":
      return "Identify recommenders; portal will invite them directly (system never contacts them).";
    case "resume":
    case "cv":
      return "Register or refresh the resume source document; writing cycle will then tailor it.";
    case "writing_sample":
    case "portfolio":
      return "Register a writing sample or portfolio source document for this revision.";
    default:
      return "Resolve the missing input before the packet can be ready for review.";
  }
}

function readyForSubmissionItem(
  packet: ApplicationPacket
): ApprovalItem | null {
  if (packet.readiness.status !== "ready_for_review") return null;

  return {
    id: approvalId(packet, "ready_for_submission"),
    actionType: "ready_for_submission",
    status: "pending",
    defaultAction: "approve",
    userId: packet.userId,
    programId: packet.programId,
    universityId: packet.universityId,
    fundingId: packet.fundingId,
    artifactId: null,
    artifactKind: null,
    reason: `All ${packet.readiness.readyItems} required items are ready and grounding audits passed.`,
    actionRequired:
      "User confirms packet is assembled and ready for the manual submission flow. The system still does not submit.",
    grounding: null,
    evidence: evidenceSummaryForPacket(packet, null),
    checklistItemIds: packet.checklist.map((item) => item.id),
    createdAt: dbClient.now()
  };
}

export function buildApprovalQueue(
  input: ApprovalQueueBuildInput
): ApprovalItem[] {
  const items: ApprovalItem[] = [];
  const { packet } = input;

  for (const checklistItem of packet.checklist) {
    const approve = approveDraftItem(packet, checklistItem);
    if (approve) items.push(approve);

    const edit = editRequiredItem(packet, checklistItem);
    if (edit) items.push(edit);
  }

  for (const missing of missingInputItems(packet)) {
    items.push(missing);
  }

  const ready = readyForSubmissionItem(packet);
  if (ready) items.push(ready);

  return items;
}

export function emptyQueueTotals(): Record<ApprovalActionType, number> {
  return {
    approve_draft: 0,
    edit_required: 0,
    missing_input: 0,
    ready_for_submission: 0
  };
}

export function tallyQueue(
  items: readonly ApprovalItem[]
): Record<ApprovalActionType, number> {
  const totals = emptyQueueTotals();
  for (const item of items) {
    totals[item.actionType] += 1;
  }
  return totals;
}
